import re
from playwright.sync_api import Page, expect

def test_example(page: Page) -> None:
    page.goto("https://petstore.octoperf.com/")

    # 验证petstore网站 title正确
    print('title:'+ page.title())
    assert "JPetStore Demo" in page.title()


    page.get_by_role("link", name="Enter the Store").click()
    page.get_by_role("link", name="Sign In").click()
    page.locator('[name="username"]').click()
    page.locator('[name="username"]').fill("angel")
    page.locator("input[name=\"password\"]").fill("123456")
    page.get_by_role("button", name="Login").click()
    page.locator("#WelcomeContent").click()
    welcome_text= page.locator("#WelcomeContent").text_content()
    print(welcome_text)
    # 验证登录用户欢迎语正确
    assert "Welcome Angel" in welcome_text

    # page.get_by_role("link", name="My Account").click()
    # page.get_by_role("link", name="Sign Out").click()
    # page.get_by_text("Saltwater, Freshwater Various").click()
    # page.locator("#SidebarContent").get_by_role("link").nth(1).click()
    # page.locator("#BackLink").click()
    # page.get_by_role("textbox").click()
    # page.get_by_role("textbox").fill("cat")
    # page.get_by_role("button", name="Search").click()
    # page.locator("#QuickLinks").get_by_role("link").nth(3).click()
    # page.locator("#QuickLinks").get_by_role("link").nth(1).click()
    # page.get_by_role("textbox").dblclick()
    # page.get_by_role("textbox").fill("dog")
    # page.get_by_role("button", name="Search").click()
    # page.locator("#QuickLinks").get_by_role("link").first.click()
    # page.get_by_role("link", name="FI-SW-01").click()
    # page.get_by_role("link", name="EST-1").click()
    # page.get_by_role("link", name="Return to FI-SW-").click()
    # page.get_by_role("link", name="Add to Cart").first.click()
    # page.locator("input[name=\"EST-1\"]").dblclick()
    # page.locator("input[name=\"EST-1\"]").fill("2")
    # page.locator("#Catalog").click()
    # page.get_by_role("button", name="Update Cart").click()
    # page.locator("input[name=\"EST-1\"]").dblclick()
    # page.locator("input[name=\"EST-1\"]").fill("5")
    # page.get_by_role("link", name="Proceed to Checkout").click()
    # page.locator("input[name=\"password\"]").dblclick()
    # page.locator("input[name=\"password\"]").fill("123456")
    # page.get_by_role("button", name="Login").click()
    # page.locator("#MenuContent").get_by_role("link").filter(has_text=re.compile(r"^$")).click()
    # page.locator("input[name=\"EST-1\"]").dblclick()
    # page.locator("input[name=\"EST-1\"]").fill("5")
    # page.get_by_role("cell", name="Sub Total: $33.00 Update Cart").click()
    # page.get_by_role("link", name="Proceed to Checkout").click()
    # page.get_by_role("cell", name="Ship to different address...").click()
    # page.get_by_role("checkbox").check()
    # page.get_by_role("button", name="Continue").click()
    # page.locator("input[name=\"order\\.shipAddress1\"]").click()
    # page.locator("input[name=\"order\\.shipAddress2\"]").click()
    # page.locator("input[name=\"order\\.shipAddress2\"]").fill("4th street")
    # page.locator("input[name=\"order\\.shipAddress1\"]").click()
    # page.get_by_role("button", name="Continue").click()
    # page.get_by_role("link", name="Confirm").click()
    # page.get_by_text("Thank you, your order has").click()
    # page.get_by_role("link", name="Return to Main Menu").click()
    # page.locator("#MenuContent").get_by_role("link").filter(has_text=re.compile(r"^$")).click()
    # page.get_by_role("button", name="Update Cart").click()
    # page.get_by_role("link", name="Return to Main Menu").click()
