import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://letcode.in/test")
    page.get_by_role("link", name="Work-Space").click()
    page.get_by_text("Products").click()
    page.get_by_text("Grooming").click()
    page.get_by_role("link", name="Courses").click()
    page.get_by_role("link", name="Contact").click()
    page.get_by_role("link", name="Ortoni Report").click(button="right")
    page.get_by_role("link", name="Page Object Model").click()
    page.get_by_role("img", name="Mens Casual Slim Fit").click()
    page.get_by_role("button", name=" Products").click()
    page.get_by_role("button", name="₹ 55.99").click()
    page.get_by_role("button", name=" Add to Cart").click()
    page.get_by_role("button", name="").click()
    page.get_by_role("button", name="+").click()
    page.get_by_role("cell", name="$111.98").click()
    page.get_by_role("button", name="-").click()
    page.get_by_role("button", name="").click()
    page.get_by_role("button", name="Continue Shopping").click()
    page.get_by_role("button", name="₹ 55.99").click()
    page.get_by_role("button", name=" Add to Cart").click()
    page.get_by_role("button", name=" Add to Cart").click()
    page.get_by_role("button", name=" Add to Cart").click()
    page.get_by_role("button", name="").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Checkout").click()
    page.get_by_role("button", name="Continue Shopping").click()
    page.get_by_role("button", name="").click()
    page.get_by_role("button", name=" Products").click()
    page.get_by_role("button", name="").click()
    page.get_by_text("Username: mor_2314").click()
    page.get_by_role("textbox", name="Enter Username").click()
    page.get_by_role("textbox", name="Enter Username").fill("mor_2314")
    page.get_by_role("textbox", name="Enter Password").click()
    page.get_by_role("textbox", name="Enter Password").fill("83r5^_")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="₹ 109.95").click()
    page.get_by_role("button", name=" Add to Cart").click()
    page.get_by_role("button", name="").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Checkout").click()
    page.get_by_role("link", name="Fakestoreapi").click()
    page.goto("https://letcode.in/cart")
    page.get_by_role("button", name=" Products").click()
    page.get_by_role("link", name="Work-Space").click()
    page.get_by_role("link", name="AUI - 2").click()
    page.locator("#droppable").click()
    page.get_by_text("Drag me to my target").click()
    page.locator("#draggable").click()
    page.get_by_role("link", name="Work-Space").click()
    page.get_by_role("link", name="All in One").click()
    page.get_by_role("link", name="Work-Space").click()
    page.get_by_role("link", name="Edit").click()
    page.get_by_role("link", name="Work-Space").click()
